trigger:
  - main

variables:
  acrLoginServer: 'appcontainerm2m.azurecr.io'
  imageName: 'spring-app'
  tag: $(Build.BuildId)
  resourceGroup: 'app'
  containerAppName: 'appcontainer'

stages:

  - stage: BuildPush
    displayName: 'Build & Push Image to ACR'
    jobs:
      - job: Build
        pool:
          name: MyLocalAgent
        steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Build and Push to ACR'
            inputs:
              containerRegistry: 'acr-connection-a'
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: Dockerfile
              tags: |
                $(tag)
                latest

  - stage: Deploy
    displayName: 'Deploy to Container Apps'
    dependsOn: BuildPush
    jobs:
      - job: Deploy
        pool:
          name: MyLocalAgent
        steps:
          - task: AzureCLI@2
            displayName: 'Update Container App'
            inputs:
              azureSubscription: 'azuregroup'
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                az containerapp update `
                  --name $(containerAppName) `
                  --resource-group $(resourceGroup) `
                  --image $(acrLoginServer)/$(imageName):$(tag)